// see https://www.sbsolver.com/s/2719
export default {
    centerLetter: "l",
    edgeLetters: ["b", "e", "i", "m", "o", "z"],
    maxScore: 139,
    words: [
        "belie",
        "bell",
        "belle",
        "bezel",
        "bible",
        "bile",
        "bill",
        "blob",
        "bloom",
        "bobble",
        "boil",
        "boll",
        "bolo",
        "embezzle",
        "emblem",
        "immobile",
        "immobilize",
        "libel",
        "libelee",
        "limb",
        "limbo",
        "lime",
        "limo",
        "lobe",
        "lobo",
        "loll",
        "loom",
        "melee",
        "mile",
        "mill",
        "mobile",
        "mobilize",
        "moil",
        "mole",
        "moll",
        "oleo",
        "olio",
        "ollie",
    ],
    pangrams: [
        "mobilize",
        "immobilize",
    ],
};
